"""
Django settings for ship_tracking_api project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#k#+legf+rvh9(cdh#jg8261rumkz%hud#g@e9nk9fl87wcfx0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'tracking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ship_tracking_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ship_tracking_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("SQL_ENGINE"),
        "NAME": os.getenv("SQL_DATABASE"),
        "USER": os.getenv("SQL_USER"),
        "PASSWORD": os.getenv("SQL_PASSWORD"),
        "HOST": os.getenv("SQL_HOST"),
        "PORT": os.getenv("SQL_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COUNTRIES_OVERRIDE = {
    'AF': _('Афганистан'),
    'AX': _('Аландские острова'),
    'AL': _('Албания'),
    'DZ': _('Алжир'),
    'AS': _('Американское Самоа'),
    'AD': _('Андорра'),
    'AO': _('Ангола'),
    'AI': _('Ангилья'),
    'AQ': _('Антарктика'),
    'AG': _('Антигуа и Барбуда'),
    'AR': _('Аргентина'),
    'AM': _('Армения'),
    'AW': _('Аруба'),
    'AU': _('Австралия'),
    'AT': _('Австрия'),
    'AZ': _('Азербайджан'),
    'BS': _('Багамы'),
    'BH': _('Бахрейн'),
    'BD': _('Бангладеш'),
    'BB': _('Барбадос'),
    'BY': _('Беларусь'),
    'BE': _('Бельгия'),
    'BZ': _('Белиз'),
    'BJ': _('Бенин'),
    'BM': _('Бермудские острова'),
    'BT': _('Бутан'),
    'BO': _('Боливия'),
    'BA': _('Босния и Герцеговина'),
    'BW': _('Ботсвана'),
    'BV': _('Остров Буве'),
    'BR': _('Бразилия'),
    'IO': _('Британская территория в Индийском океане'),
    'BN': _('Бруней-Даруссалам'),
    'BG': _('Болгария'),
    'BF': _('Буркина-Фасо'),
    'BI': _('Бурунди'),
    'KH': _('Камбоджа'),
    'CM': _('Камерун'),
    'CA': _('Канада'),
    'CV': _('Кабо-Верде'),
    'KY': _('Каймановы острова'),
    'CF': _('Центральноафриканская Республика'),
    'TD': _('Чад'),
    'CL': _('Чили'),
    'CN': _('Китай'),
    'CX': _('Остров Рождества'),
    'CC': _('Кокосовые острова (Килинг)'),
    'CO': _('Колумбия'),
    'KM': _('Коморы'),
    'CG': _('Конго'),
    'CD': _('Демократическая Республика Конго'),
    'CK': _('Острова Кука'),
    'CR': _('Коста-Рика'),
    'CI': _("Кот-д'Ивуар"),
    'HR': _('Хорватия'),
    'CU': _('Куба'),
    'CY': _('Кипр'),
    'CZ': _('Чехия'),
    'DK': _('Дания'),
    'DJ': _('Джибути'),
    'DM': _('Доминика'),
    'DO': _('Доминиканская Республика'),
    'EC': _('Эквадор'),
    'EG': _('Египет'),
    'SV': _('Сальвадор'),
    'GQ': _('Экваториальная Гвинея'),
    'ER': _('Эритрея'),
    'EE': _('Эстония'),
    'ET': _('Эфиопия'),
    'FK': _('Фолклендские острова'),
    'FO': _('Фарерские острова'),
    'FJ': _('Фиджи'),
    'FI': _('Финляндия'),
    'FR': _('Франция'),
    'GF': _('Французская Гвиана'),
    'PF': _('Французская Полинезия'),
    'TF': _('Французские Южные Территории'),
    'GA': _('Габон'),
    'GM': _('Гамбия'),
    'GE': _('Грузия'),
    'DE': _('Германия'),
    'GH': _('Гана'),
    'GI': _('Гибралтар'),
    'GR': _('Греция'),
    'GL': _('Гренландия'),
    'GD': _('Гренада'),
    'GP': _('Гваделупа'),
    'GU': _('Гуам'),
    'GT': _('Гватемала'),
    'GG': _('Гернси'),
    'GN': _('Гвинея'),
    'GW': _('Гвинея-Бисау'),
    'GY': _('Гайана'),
    'HT': _('Гаити'),
    'HM': _('Херд и Макдональд, острова'),
    'VA': _('Ватикан'),
    'HN': _('Гондурас'),
    'HK': _('Гонконг'),
    'HU': _('Венгрия'),
    'IS': _('Исландия'),
    'IN': _('Индия'),
    'ID': _('Индонезия'),
    'IR': _('Иран, Исламская Республика'),
    'IQ': _('Ирак'),
    'IE': _('Ирландия'),
    'IM': _('Остров Мэн'),
    'IL': _('Израиль'),
    'IT': _('Италия'),
    'JM': _('Ямайка'),
    'JP': _('Япония'),
    'JE': _('Джерси'),
    'JO': _('Иордания'),
    'KZ': _('Казахстан'),
    'KE': _('Кения'),
    'KI': _('Кирибати'),
    'KP': _('Корейская Народно-Демократическая Республика'),
    'KR': _('Корея, Республика'),
    'KW': _('Кувейт'),
    'KG': _('Киргизия'),
    'LA': _('Лаосская Народно-Демократическая Республика'),
    'LV': _('Латвия'),
    'LB': _('Ливан'),
    'LS': _('Лесото'),
    'LR': _('Либерия'),
    'LY': _('Ливийская Арабская Джамахирия'),
    'LI': _('Лихтенштейн'),
    'LT': _('Литва'),
    'LU': _('Люксембург'),
    'MO': _('Макао'),
    'MK': _('Македония, бывшая югославская республика'),
    'MG': _('Мадагаскар'),
    'MW': _('Малави'),
    'MY': _('Малайзия'),
    'MV': _('Мальдивы'),
    'ML': _('Мали'),
    'MT': _('Мальта'),
    'MH': _('Маршалловы острова'),
    'MQ': _('Мартиника'),
    'MR': _('Мавритания'),
    'MU': _('Маврикий'),
    'YT': _('Майотта'),
    'MX': _('Мексика'),
    'FM': _('Микронезия, Федеративные Штаты'),
    'MD': _('Молдавия'),
    'MC': _('Монако'),
    'MN': _('Монголия'),
    'ME': _('Черногория'),
    'MS': _('Монтсеррат'),
    'MA': _('Марокко'),
    'MZ': _('Мозамбик'),
    'MM': _('Мьянма'),
    'NA': _('Намибия'),
    'NR': _('Науру'),
    'NP': _('Непал'),
    'NL': _('Нидерланды'),
    'AN': _('Нидерландские Антильские острова'),
    'NC': _('Новая Каледония'),
    'NZ': _('Новая Зеландия'),
    'NI': _('Никарагуа'),
    'NE': _('Нигер'),
    'NG': _('Нигерия'),
    'NU': _('Ниуэ'),
    'NF': _('Норфолк'),
    'MP': _('Северные Марианские острова'),
    'NO': _('Норвегия'),
    'OM': _('Оман'),
    'PK': _('Пакистан'),
    'PW': _('Палау'),
    'PS': _('Палестинская территория, оккупированная'),
    'PA': _('Панама'),
    'PG': _('Папуа - Новая Гвинея'),
    'PY': _('Парагвай'),
    'PE': _('Перу'),
    'PH': _('Филиппины'),
    'PN': _('Питкэрн'),
    'PL': _('Польша'),
    'PT': _('Португалия'),
    'PR': _('Пуэрто-Рико'),
    'QA': _('Катар'),
    'RE': _('Реюньон'),
    'RO': _('Румыния'),
    'RU': _('Российская Федерация'),
    'RW': _('Руанда'),
    'BL': _('Сен-Бартелеми'),
    'SH': _('Остров Святой Елены'),
    'KN': _('Сент-Китс и Невис'),
    'LC': _('Сент-Люсия'),
    'MF': _('Сен-Мартен'),
    'PM': _('Сен-Пьер и Микелон'),
    'VC': _('Сент-Винсент и Гренадины'),
    'WS': _('Самоа'),
    'SM': _('Сан-Марино'),
    'ST': _('Сан-Томе и Принсипи'),
    'SA': _('Саудовская Аравия'),
    'SN': _('Сенегал'),
    'RS': _('Сербия'),
    'SC': _('Сейшелы'),
    'SL': _('Сьерра-Леоне'),
    'SG': _('Сингапур'),
    'SK': _('Словакия'),
    'SI': _('Словения'),
    'SB': _('Соломоновы острова'),
    'SO': _('Сомали'),
    'ZA': _('Южно-Африканская Республика'),
    'GS': _('Южная Джорджия и Южные Сандвичевы острова'),
    'ES': _('Испания'),
    'LK': _('Шри-Ланка'),
    'SD': _('Судан'),
    'SR': _('Суринам'),
    'SJ': _('Шпицберген и Ян-Майен'),
    'SZ': _('Эсватини'),
    'SE': _('Швеция'),
    'CH': _('Швейцария'),
    'SY': _('Сирийская Арабская Республика'),
    'TW': _('Тайвань, провинция Китая'),
    'TJ': _('Таджикистан'),
    'TZ': _('Объединенная Республика Танзания'),
    'TH': _('Таиланд'),
    'TL': _('Восточный Тимор'),
    'TG': _('Того'),
    'TK': _('Токелау'),
    'TO': _('Тонга'),
    'TT': _('Тринидад и Тобаго'),
    'TN': _('Тунис'),
    'TR': _('Турция'),
    'TM': _('Туркменистан'),
    'TC': _('Теркс и Кайкос'),
    'TV': _('Тувалу'),
    'UG': _('Уганда'),
    'UA': _('Украина'),
    'AE': _('Объединенные Арабские Эмираты'),
    'GB': _('Великобритания'),
    'US': _('Соединенные Штаты Америки'),
    'UM': _('Внешние малые острова США'),
    'UY': _('Уругвай'),
    'UZ': _('Узбекистан'),
    'VU': _('Вануату'),
    'VE': _('Венесуэла'),
    'VN': _('Вьетнам'),
    'VG': _('Виргинские острова, Британские'),
    'VI': _('Виргинские острова, США'),
    'WF': _('Уоллис и Футуна'),
    'EH': _('Западная Сахара'),
    'YE': _('Йемен'),
    'ZM': _('Замбия'),
    'ZW': _('Зимбабве'),
}
