# Generated by Django 4.2 on 2023-04-08 14:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код судна')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тоннаж')),
                ('type', models.CharField(choices=[('container_ship', 'Контейнеровоз'), ('bulk_carrier', 'Сухогруз'), ('oil_tanker', 'Нефтяной танкер'), ('gas_carrier', 'Газовоз'), ('chemical_tanker', 'Химический танкер'), ('reefer_ship', 'Рефрижераторный судно'), ('cruise_ship', 'Круизный лайнер'), ('ferry', 'Паром'), ('yacht', 'Яхта'), ('tugboat', 'Буксир')], max_length=50, verbose_name='Тип судана')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('авария', 'Авария'), ('захват', 'Захват'), ('пожар', 'Пожар'), ('потеря', 'Потеря'), ('поломка', 'Поломка')], max_length=50)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.ship')),
            ],
        ),
    ]
