# Generated by Django 4.2 on 2023-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='name',
        ),
        migrations.AlterField(
            model_name='ship',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Номер ИМО'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Долгота'),
        ),
    ]
