# Generated by Django 4.2 on 2023-04-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='type',
            field=models.CharField(choices=[('container_ship', 'Контейнеровоз'), ('bulk_carrier', 'Сухогруз'), ('oil_tanker', 'Нефтяной танкер'), ('gas_carrier', 'Газовоз'), ('chemical_tanker', 'Химический танкер'), ('reefer_ship', 'Рефрижераторное судно'), ('cruise_ship', 'Круизный лайнер'), ('ferry', 'Паром'), ('yacht', 'Яхта'), ('tugboat', 'Буксир')], max_length=50, verbose_name='Тип судана'),
        ),
    ]
