# Generated by Django 4.2 on 2023-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_event_latitude_event_longitude_alter_ship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='codename',
            field=models.CharField(blank=True, max_length=20, verbose_name='Позывной'),
        ),
        migrations.AddField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
