# Generated by Django 4.2 on 2023-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_ship_codename_ship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='type',
            field=models.CharField(choices=[('container_ship', 'Контейнеровоз'), ('oil_tanker', 'Нефтяной танкер'), ('cruise_ship', 'Круизный лайнер'), ('ferry', 'Паром'), ('yacht', 'Яхта')], max_length=50, verbose_name='Тип судана'),
        ),
    ]
