# Generated by Django 4.2 on 2023-04-12 10:25

from django.db import migrations

ports = [dict(name='Порт Роттердама', code='NLRTM', latitude=51.94331, longitude=4.141812, country='NL'),
         dict(name='Порт Шанхая', code='CNSHA', latitude=31.366365, longitude=121.61475, country='CN'),
         dict(name='Порт Порт-Хедленда', code='AUPHE', latitude=-20.3165, longitude=118.576, country='AU'),
         dict(name='Порт Ричардс-Бей', code='ZARCB', latitude=-28.806, longitude=32.06, country='ZA'),
         dict(name='Порт Хьюстона', code='USHOU', latitude=29.72779, longitude=-95.27004, country='US')]


def forwards(apps, *args):
    Port = apps.get_model('tracking', 'Port')
    for i in ports:
        port = Port.objects.create(
            name=i.get('name'),
            code=i.get('code'),
            latitude=i.get('latitude'),
            longitude=i.get('longitude'),
            country=i.get('country'),
        )
        port.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0007_port'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
